apiVersion: batch/v1
kind: Job
metadata:
  generateName: terrascan-hook-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      volumes:
      - name: secret-volume
        configMap:
          name: skip-rule
       
      containers:
      - name: terrascan-argocd
        image: accurics/terrascan:latest
        command: ["/bin/ash", "-c"]
        args:
        - >
          /go/bin/terrascan scan -r git -u https://github.com/murital/argocdtest.git -i k8s -t k8s 
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"

      
      restartPolicy: Never
  backoffLimit: 1
